version: '3'

# This file allows you to test the app and updater in a development environment.
#
# So, in order to function correctly in your development environment, you need to use the same
# value of API_KEY as the secret, or simply specify the same API_KEY environment variable for
# both the web and updater services.
#
# See updater-image/update.sh for details of the namespace and secret.
#
# Pre-requisites:
#
#   .env.docker-compose - defining AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and GITHUB_TOKEN

services:
  web:
    build: .
    ports:
      - "4567:4567"
    environment:
      RACK_ENV: production
      API_KEY: wibble

  # This service will usually do nothing on `docker-compose up`, but defining it here means
  # you can run `docker-compose run updater /app/update.sh` manually.
  updater:
    build: updater-image
    depends_on:
      - web
    env_file:
      - .env.docker-compose  # AWS creds & GitHub API token
    environment:
      API_KEY: wibble
      AWS_REGION: eu-west-2
      KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
      KUBECONFIG_S3_KEY: kubeconfig
      KUBECONFIG: /tmp/kubeconfig
      KUBE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
      DATA_URL: http://web:4567
      DOCUMENTATION_SITES: "https://runbooks.cloud-platform.service.justice.gov.uk https://user-guide.cloud-platform.service.justice.gov.uk"
